=== dgf0007/Lenguaje-de-Marcas/Trimestre-2/XML/first/libro.dtd
<!-- * es 0 o mas-->
<!-- + es 1 o mas-->
<!-- 0 o 1-->

<!-- Los atributos tmb hay que definirlos-->
<!-- #Required; Es un campo requerido-->
<!-- #impi3e: -->
<!-- #valor-->

<!ELEMENT biblioteca (libro)+>
<!ATTLIST biblioteca ciudad CDATA #REQUIRED>

<!ELEMENT libro (titulo, (autor|autora), paginas, editorial?, categoria*)> <!-- En el mismo orden que en el html-->
<!ATTLIST libro formato CDATA "tapa blanda"> <!-- Valor por defecto-->
<!-- La interrogaciÃ³n al final, indica que puede tener editorial o no-->
<!-- El asterisco al final, indica que puede tener mas de un elemento (categoria)-->

<!ELEMENT titulo (#PCDATA)>
<!ATTLIST titulo subtitulo CDATA #IMPLIED> <!-- Valor opcional-->
<!ELEMENT autor (#PCDATA)>
<!ELEMENT autora (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>

=== dgf0007/Lenguaje-de-Marcas/Trimestre-2/XML/first/first.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style.css" type="text/css"?>

<!DOCTYPE biblioteca SYSTEM "libro.dtd"> <!-- Para validar se recomienda quitar errores de abajo a arriba-->

<biblioteca ciudad="Malaga"> <!-- Es como una class o id-->
    <libro formato="tapa dura">
    <titulo subtitulo="De Medac">El famacéutico</titulo>
    <autor>Newt</autor>
    <paginas>50</paginas>
    <categoria>Acción</categoria>
    <categoria>salute</categoria>
</libro>

<libro formato="tapa blanda">
    <titulo>Von Neuman</titulo>
    <autora>Salvadora</autora>
    <paginas>10</paginas>
    <editorial>Sistemas</editorial>
    
</libro>
</biblioteca>
